import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

export type Database = {
  clients: {
    id: string;
    user_id: string;
    name: string;
    contact_person: string | null;
    email: string | null;
    phone: string | null;
    location: string | null;
    website: string | null;
    industry: string | null;
    status: string;
    notes: string | null;
    tags: string[];
    created_at: string;
    updated_at: string;
  };
  projects: {
    id: string;
    user_id: string;
    client_id: string | null;
    name: string;
    description: string | null;
    project_type: string;
    status: string;
    priority: string;
    progress: number;
    start_date: string | null;
    expected_completion_date: string | null;
    actual_completion_date: string | null;
    budget: number;
    amount_charged: number;
    amount_paid: number;
    project_manager: string | null;
    tags: string[];
    technologies: string[];
    is_archived: boolean;
    is_pinned: boolean;
    is_portfolio_public: boolean;
    created_at: string;
    updated_at: string;
  };
  tasks: {
    id: string;
    user_id: string;
    project_id: string | null;
    client_id: string | null;
    title: string;
    description: string | null;
    assigned_to: string | null;
    priority: string;
    status: string;
    due_date: string | null;
    start_date: string | null;
    tags: string[];
    checklist: any[];
    is_complete: boolean;
    created_at: string;
    updated_at: string;
  };
  websites: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    name: string;
    url: string | null;
    status: string;
    domain: string | null;
    registrar: string | null;
    hosting_provider: string | null;
    hosting_expiry: string | null;
    domain_expiry: string | null;
    ssl_expiry: string | null;
    technology: string | null;
    framework: string | null;
    cms: string | null;
    repository: string | null;
    deployment_platform: string | null;
    developer: string | null;
    launch_date: string | null;
    maintenance_status: string;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  applications: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    name: string;
    version: string | null;
    platform: string | null;
    status: string;
    technology_stack: string | null;
    repository: string | null;
    production_url: string | null;
    staging_url: string | null;
    api_url: string | null;
    database: string | null;
    hosting: string | null;
    deployment_system: string | null;
    developer: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  pos_systems: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    name: string;
    business_name: string | null;
    version: string | null;
    hardware_info: string | null;
    software_info: string | null;
    database: string | null;
    server: string | null;
    repository: string | null;
    deployment_info: string | null;
    installation_date: string | null;
    license_info: string | null;
    support_status: string;
    maintenance_status: string;
    branches: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  repositories: {
    id: string;
    user_id: string;
    project_id: string | null;
    client_id: string | null;
    name: string;
    provider: string;
    url: string;
    main_language: string | null;
    framework: string | null;
    branch: string;
    deployment_environment: string | null;
    production_status: string;
    last_update: string | null;
    developer: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  domains: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    domain: string;
    registrar: string | null;
    registration_date: string | null;
    expiry_date: string | null;
    auto_renewal: boolean;
    dns_provider: string | null;
    nameservers: string | null;
    ssl_status: string;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  hosting: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    provider: string;
    server: string | null;
    plan: string | null;
    start_date: string | null;
    renewal_date: string | null;
    cost: number;
    status: string;
    server_location: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  documents: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    name: string;
    category: string;
    file_type: string | null;
    file_size: number | null;
    description: string | null;
    tags: string[];
    version: number;
    storage_path: string | null;
    created_at: string;
    updated_at: string;
  };
  contracts: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    title: string;
    contract_type: string | null;
    start_date: string | null;
    end_date: string | null;
    value: number;
    status: string;
    renewal_date: string | null;
    signed_date: string | null;
    signatories: string | null;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  invoices: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    invoice_number: string;
    issue_date: string | null;
    due_date: string | null;
    subtotal: number;
    tax: number;
    discount: number;
    total: number;
    amount_paid: number;
    payment_status: string;
    notes: string | null;
    created_at: string;
    updated_at: string;
  };
  payments: {
    id: string;
    user_id: string;
    invoice_id: string | null;
    client_id: string | null;
    project_id: string | null;
    amount: number;
    payment_date: string;
    payment_method: string | null;
    reference: string | null;
    notes: string | null;
    created_at: string;
  };
  expenses: {
    id: string;
    user_id: string;
    project_id: string | null;
    client_id: string | null;
    description: string;
    amount: number;
    expense_date: string;
    category: string | null;
    vendor: string | null;
    notes: string | null;
    created_at: string;
  };
  meetings: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    title: string;
    meeting_date: string;
    meeting_time: string | null;
    participants: string | null;
    meeting_type: string | null;
    agenda: string | null;
    notes: string | null;
    decisions: string | null;
    action_items: string | null;
    follow_up_date: string | null;
    created_at: string;
    updated_at: string;
  };
  communications: {
    id: string;
    user_id: string;
    client_id: string | null;
    project_id: string | null;
    type: string;
    sender: string | null;
    recipient: string | null;
    subject: string | null;
    body: string | null;
    communication_date: string;
    attachments: string | null;
    notes: string | null;
    created_at: string;
  };
  notes: {
    id: string;
    user_id: string;
    project_id: string | null;
    client_id: string | null;
    title: string;
    content: string | null;
    is_internal: boolean;
    created_at: string;
    updated_at: string;
  };
  activities: {
    id: string;
    user_id: string;
    action: string;
    entity_type: string | null;
    entity_id: string | null;
    entity_name: string | null;
    project_id: string | null;
    client_id: string | null;
    metadata: any;
    created_at: string;
  };
  team_members: {
    id: string;
    user_id: string;
    name: string;
    email: string | null;
    role: string;
    department: string | null;
    profile: string | null;
    permissions: any;
    created_at: string;
    updated_at: string;
  };
  knowledge_base: {
    id: string;
    user_id: string;
    title: string;
    category: string;
    content: string | null;
    tags: string[];
    created_at: string;
    updated_at: string;
  };
};

export type TableName = keyof Database;
