import {
  Globe2,
  CreditCard,
  Database,
  ShieldCheck,
  FileText,
  BookOpen,
  LifeBuoy,
  Archive,
  BriefcaseBusiness,
  CalendarDays,
  Activity,
} from 'lucide-react';
import { ResourcePage } from '@/pages/ResourcePage';
import type { ResourceConfig } from '@/pages/ResourcePage';

export const websitesConfig: ResourceConfig = {
  table: 'websites',
  title: 'Websites',
  subtitle: 'Project assets',
  entityLabel: 'Website',
  icon: Globe2,
  searchFields: ['name', 'url', 'domain', 'technology', 'framework'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.url ?? 'No URL',
  cardBadge: (r) => r.status,
  cardFields: [
    { label: 'Domain', value: (r) => r.domain },
    { label: 'Technology', value: (r) => r.technology },
    { label: 'Framework', value: (r) => r.framework },
    { label: 'Hosting', value: (r) => r.hosting_provider },
  ],
  fields: [
    { key: 'name', label: 'Website name', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'url', label: 'URL' },
    { key: 'status', label: 'Status', type: 'select', options: ['Live', 'In Development', 'Staging', 'Maintenance', 'Down', 'Archived'] },
    { key: 'domain', label: 'Domain' },
    { key: 'registrar', label: 'Registrar' },
    { key: 'hosting_provider', label: 'Hosting provider' },
    { key: 'technology', label: 'Technology' },
    { key: 'framework', label: 'Framework' },
    { key: 'cms', label: 'CMS' },
    { key: 'repository', label: 'Repository URL' },
    { key: 'deployment_platform', label: 'Deployment platform' },
    { key: 'developer', label: 'Developer' },
    { key: 'launch_date', label: 'Launch date', type: 'date' },
    { key: 'domain_expiry', label: 'Domain expiry', type: 'date' },
    { key: 'hosting_expiry', label: 'Hosting expiry', type: 'date' },
    { key: 'ssl_expiry', label: 'SSL expiry', type: 'date' },
    { key: 'maintenance_status', label: 'Maintenance status', type: 'select', options: ['None', 'Active', 'On Hold', 'Ended'] },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
  ],
};

export const applicationsConfig: ResourceConfig = {
  table: 'applications',
  title: 'Applications',
  subtitle: 'Project assets',
  entityLabel: 'Application',
  icon: CreditCard,
  searchFields: ['name', 'version', 'platform', 'technology_stack'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.version ? `v${r.version}` : 'No version',
  cardBadge: (r) => r.status,
  cardFields: [
    { label: 'Platform', value: (r) => r.platform },
    { label: 'Tech stack', value: (r) => r.technology_stack },
    { label: 'Production', value: (r) => r.production_url },
  ],
  fields: [
    { key: 'name', label: 'Application name', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'version', label: 'Version' },
    { key: 'platform', label: 'Platform', type: 'select', options: ['Web', 'iOS', 'Android', 'Desktop', 'Cross-platform', 'API', 'Other'] },
    { key: 'status', label: 'Status', type: 'select', options: ['In Development', 'Testing', 'Deployed', 'Maintenance', 'Deprecated', 'Archived'] },
    { key: 'technology_stack', label: 'Technology stack' },
    { key: 'repository', label: 'Repository URL' },
    { key: 'production_url', label: 'Production URL' },
    { key: 'staging_url', label: 'Staging URL' },
    { key: 'api_url', label: 'API URL' },
    { key: 'database', label: 'Database' },
    { key: 'hosting', label: 'Hosting' },
    { key: 'deployment_system', label: 'Deployment system' },
    { key: 'developer', label: 'Developer' },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
  ],
};

export const posConfig: ResourceConfig = {
  table: 'pos_systems',
  title: 'POS Systems',
  subtitle: 'Project assets',
  entityLabel: 'POS System',
  icon: Database,
  searchFields: ['name', 'business_name', 'version', 'hardware_info'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.business_name ?? 'No business',
  cardBadge: (r) => r.support_status,
  cardFields: [
    { label: 'Version', value: (r) => r.version },
    { label: 'Server', value: (r) => r.server },
    { label: 'Installed', value: (r) => r.installation_date },
  ],
  fields: [
    { key: 'name', label: 'POS name', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'business_name', label: 'Business name' },
    { key: 'version', label: 'Version' },
    { key: 'hardware_info', label: 'Hardware info' },
    { key: 'software_info', label: 'Software info' },
    { key: 'database', label: 'Database' },
    { key: 'server', label: 'Server' },
    { key: 'repository', label: 'Repository URL' },
    { key: 'deployment_info', label: 'Deployment info' },
    { key: 'installation_date', label: 'Installation date', type: 'date' },
    { key: 'license_info', label: 'License info' },
    { key: 'support_status', label: 'Support status', type: 'select', options: ['Active', 'On Hold', 'Ended', 'Trial'] },
    { key: 'maintenance_status', label: 'Maintenance status', type: 'select', options: ['None', 'Active', 'On Hold', 'Ended'] },
    { key: 'branches', label: 'Branches' },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
  ],
};

export const repositoriesConfig: ResourceConfig = {
  table: 'repositories',
  title: 'Repositories',
  subtitle: 'Project assets',
  entityLabel: 'Repository',
  icon: Database,
  searchFields: ['name', 'provider', 'url', 'main_language', 'framework'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.provider,
  cardBadge: (r) => r.production_status,
  cardFields: [
    { label: 'Language', value: (r) => r.main_language },
    { label: 'Framework', value: (r) => r.framework },
    { label: 'Branch', value: (r) => r.branch },
  ],
  fields: [
    { key: 'name', label: 'Repository name', required: true },
    { key: 'project_id', label: 'Project' },
    { key: 'client_id', label: 'Client' },
    { key: 'provider', label: 'Provider', type: 'select', options: ['GitHub', 'GitLab', 'Bitbucket', 'Other'] },
    { key: 'url', label: 'Repository URL', required: true },
    { key: 'main_language', label: 'Main language' },
    { key: 'framework', label: 'Framework' },
    { key: 'branch', label: 'Branch' },
    { key: 'deployment_environment', label: 'Deployment environment' },
    { key: 'production_status', label: 'Production status', type: 'select', options: ['Active', 'Inactive', 'Deployed', 'Failed'] },
    { key: 'last_update', label: 'Last update', type: 'date' },
    { key: 'developer', label: 'Developer' },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
  ],
};

export const documentsConfig: ResourceConfig = {
  table: 'documents',
  title: 'Documents',
  subtitle: 'Documents & records',
  entityLabel: 'Document',
  icon: FileText,
  searchFields: ['name', 'category', 'description', 'file_type'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.category,
  cardBadge: (r) => r.file_type,
  cardFields: [
    { label: 'Version', value: (r) => `v${r.version}` },
    { label: 'Description', value: (r) => r.description },
  ],
  fields: [
    { key: 'name', label: 'Document name', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'category', label: 'Category', type: 'select', options: ['Contracts', 'Agreements', 'Proposals', 'Quotes', 'Invoices', 'Receipts', 'Requirements', 'Specifications', 'Designs', 'Reports', 'Manuals', 'Technical Documentation', 'Meeting Minutes', 'Client Documents', 'Legal Documents', 'Business Documents', 'Project Files', 'Other'] },
    { key: 'file_type', label: 'File type' },
    { key: 'description', label: 'Description', type: 'textarea', full: true },
    { key: 'tags', label: 'Tags (comma-separated)', full: true },
  ],
};

export const contractsConfig: ResourceConfig = {
  table: 'contracts',
  title: 'Contracts',
  subtitle: 'Documents & records',
  entityLabel: 'Contract',
  icon: FileText,
  searchFields: ['title', 'contract_type', 'status', 'signatories'],
  cardTitle: (r) => r.title,
  cardSubtitle: (r) => r.contract_type ?? 'No type',
  cardBadge: (r) => r.status,
  cardFields: [
    { label: 'Value', value: (r) => r.value ? `$${Number(r.value).toLocaleString()}` : null },
    { label: 'Start', value: (r) => r.start_date },
    { label: 'End', value: (r) => r.end_date },
  ],
  fields: [
    { key: 'title', label: 'Contract title', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'contract_type', label: 'Contract type', type: 'select', options: ['Service Agreement', 'NDA', 'SLA', 'Maintenance', 'Development', 'Consulting', 'Other'] },
    { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Sent', 'Awaiting Signature', 'Signed', 'Active', 'Expiring Soon', 'Expired', 'Cancelled'] },
    { key: 'value', label: 'Value ($)', type: 'number' },
    { key: 'start_date', label: 'Start date', type: 'date' },
    { key: 'end_date', label: 'End date', type: 'date' },
    { key: 'signed_date', label: 'Signed date', type: 'date' },
    { key: 'renewal_date', label: 'Renewal date', type: 'date' },
    { key: 'signatories', label: 'Signatories' },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
  ],
};

export const meetingsConfig: ResourceConfig = {
  table: 'meetings',
  title: 'Meeting Notes',
  subtitle: 'Documents & records',
  entityLabel: 'Meeting',
  icon: BookOpen,
  searchFields: ['title', 'participants', 'meeting_type', 'agenda', 'decisions', 'action_items'],
  cardTitle: (r) => r.title,
  cardSubtitle: (r) => r.meeting_date,
  cardBadge: (r) => r.meeting_type,
  cardFields: [
    { label: 'Time', value: (r) => r.meeting_time },
    { label: 'Participants', value: (r) => r.participants },
    { label: 'Follow-up', value: (r) => r.follow_up_date },
  ],
  fields: [
    { key: 'title', label: 'Meeting title', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'meeting_date', label: 'Date', type: 'date', required: true },
    { key: 'meeting_time', label: 'Time' },
    { key: 'meeting_type', label: 'Type', type: 'select', options: ['Client Meeting', 'Internal', 'Review', 'Planning', 'Discovery', 'Demo', 'Other'] },
    { key: 'participants', label: 'Participants' },
    { key: 'agenda', label: 'Agenda', type: 'textarea', full: true },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
    { key: 'decisions', label: 'Decisions', type: 'textarea', full: true },
    { key: 'action_items', label: 'Action items', type: 'textarea', full: true },
    { key: 'follow_up_date', label: 'Follow-up date', type: 'date' },
  ],
};

export const communicationsConfig: ResourceConfig = {
  table: 'communications',
  title: 'Communications',
  subtitle: 'Main',
  entityLabel: 'Communication',
  icon: Activity,
  searchFields: ['type', 'sender', 'recipient', 'subject', 'body'],
  cardTitle: (r) => r.subject ?? r.type,
  cardSubtitle: (r) => `${r.sender ?? ''} → ${r.recipient ?? ''}`,
  cardBadge: (r) => r.type,
  cardFields: [
    { label: 'Date', value: (r) => r.communication_date },
    { label: 'Type', value: (r) => r.type },
  ],
  fields: [
    { key: 'type', label: 'Type', type: 'select', options: ['Email', 'Phone call', 'WhatsApp', 'Meeting', 'SMS', 'Internal note', 'Client message'] },
    { key: 'client_id', label: 'Client' },
    { key: 'project_id', label: 'Project' },
    { key: 'sender', label: 'Sender' },
    { key: 'recipient', label: 'Recipient' },
    { key: 'subject', label: 'Subject' },
    { key: 'communication_date', label: 'Date', type: 'date' },
    { key: 'body', label: 'Body / content', type: 'textarea', full: true },
    { key: 'attachments', label: 'Attachments' },
    { key: 'notes', label: 'Notes', type: 'textarea', full: true },
  ],
};

export const knowledgeBaseConfig: ResourceConfig = {
  table: 'knowledge_base',
  title: 'Knowledge Base',
  subtitle: 'Knowledge',
  entityLabel: 'Article',
  icon: LifeBuoy,
  searchFields: ['title', 'category', 'content'],
  cardTitle: (r) => r.title,
  cardSubtitle: (r) => r.category,
  cardFields: [
    { label: 'Category', value: (r) => r.category },
  ],
  fields: [
    { key: 'title', label: 'Title', required: true },
    { key: 'category', label: 'Category', type: 'select', options: ['Development', 'Websites', 'POS', 'Applications', 'Networking', 'Hosting', 'Servers', 'Databases', 'Security', 'Business Processes', 'Client Support', 'Troubleshooting', 'SOPs'] },
    { key: 'tags', label: 'Tags (comma-separated)', full: true },
    { key: 'content', label: 'Content (Markdown supported)', type: 'textarea', full: true },
  ],
};

export const teamConfig: ResourceConfig = {
  table: 'team_members',
  title: 'Team',
  subtitle: 'Main',
  entityLabel: 'Team member',
  icon: BriefcaseBusiness,
  searchFields: ['name', 'email', 'role', 'department'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.email ?? 'No email',
  cardBadge: (r) => r.role,
  cardFields: [
    { label: 'Department', value: (r) => r.department },
    { label: 'Role', value: (r) => r.role },
  ],
  fields: [
    { key: 'name', label: 'Name', required: true },
    { key: 'email', label: 'Email' },
    { key: 'role', label: 'Role', type: 'select', options: ['Owner', 'Administrator', 'Project Manager', 'Developer', 'Designer', 'Accountant', 'Support', 'Viewer', 'Client'] },
    { key: 'department', label: 'Department' },
    { key: 'profile', label: 'Profile', type: 'textarea', full: true },
  ],
};

export const archiveConfig: ResourceConfig = {
  table: 'projects',
  title: 'Archive',
  subtitle: 'Workspace',
  entityLabel: 'Archived project',
  icon: Archive,
  searchFields: ['name', 'project_type', 'status'],
  cardTitle: (r) => r.name,
  cardSubtitle: (r) => r.project_type,
  cardBadge: (r) => r.status,
  cardFields: [
    { label: 'Completed', value: (r) => r.actual_completion_date },
    { label: 'Revenue', value: (r) => r.amount_charged ? `$${Number(r.amount_charged).toLocaleString()}` : null },
  ],
  fields: [
    { key: 'name', label: 'Project name', required: true },
    { key: 'client_id', label: 'Client' },
    { key: 'project_type', label: 'Project type' },
    { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'Cancelled', 'Archived'] },
    { key: 'description', label: 'Description', type: 'textarea', full: true },
  ],
};
